/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_selfcontrol_exeemulator_dasm */

#ifndef _Included_kr_selfcontrol_exeemulator_dasm
#define _Included_kr_selfcontrol_exeemulator_dasm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_selfcontrol_exeemulator_dasm
 * Method:    fileLoad
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kr_selfcontrol_exeemulator_dasm_fileLoad
  (JNIEnv *, jclass, jstring);

/*
 * Class:     kr_selfcontrol_exeemulator_dasm
 * Method:    getPrintBuffer
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_selfcontrol_exeemulator_dasm_getPrintBuffer
  (JNIEnv *, jclass);

/*
 * Class:     kr_selfcontrol_exeemulator_dasm
 * Method:    isFinish
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_kr_selfcontrol_exeemulator_dasm_isFinish
  (JNIEnv *, jclass);

/*
 * Class:     kr_selfcontrol_exeemulator_dasm
 * Method:    readNext
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_selfcontrol_exeemulator_dasm_readNext
  (JNIEnv *, jclass);

/*
 * Class:     kr_selfcontrol_exeemulator_dasm
 * Method:    getInputType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_kr_selfcontrol_exeemulator_dasm_getInputType
  (JNIEnv *, jclass);

/*
 * Class:     kr_selfcontrol_exeemulator_dasm
 * Method:    inputChar
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_kr_selfcontrol_exeemulator_dasm_inputChar
  (JNIEnv *, jclass, jstring);

/*
 * Class:     kr_selfcontrol_exeemulator_dasm
 * Method:    inputFloat
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_kr_selfcontrol_exeemulator_dasm_inputFloat
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     kr_selfcontrol_exeemulator_dasm
 * Method:    inputInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_kr_selfcontrol_exeemulator_dasm_inputInt
  (JNIEnv *, jclass, jint);

/*
 * Class:     kr_selfcontrol_exeemulator_dasm
 * Method:    printBufferClear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kr_selfcontrol_exeemulator_dasm_printBufferClear
  (JNIEnv *, jclass);

/*
 * Class:     kr_selfcontrol_exeemulator_dasm
 * Method:    callBackTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kr_selfcontrol_exeemulator_dasm_callBackTest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
